name: @Strilanc2 - Craig Gidney's Blog
markdown: redcarpet
pygments: true
description: A computer-science / software-engineering / programming blog with absolutely no distinguishing features.
url: http://strilanc.com

