name: "Algorithmic Assertions - Craig Gidney's Computer Science Blog"
markdown: redcarpet
highlighter: pygments
description: A blog about computer science, software engineering, quantum computing, mathematical puzzles, and so forth.
url: http://algassert.com
