name: "Algorithmic Assertions - Craig Gidney's Computer Science Blog"
markdown: kramdown
highlighter: rouge
description: A blog about computer science, software engineering, quantum computing, mathematical puzzles, and so forth.
url: http://algorithmicassertions.com

