name: "Algorithmic Assertions - Craig Gidney's Computer Science Blog"
markdown: redcarpet
pygments: true
description: A blog about computer science, software engineering, quantum computing, mathematical puzzles, and so forth.
url: http://strilanc.com

